version: '3.7'

services:
  aws-infra:
    container_name: aws-infra
    image: aws-infra
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
    volumes:
      - .:/project
    command: ["/bin/bash"]